nod-ai/iree-kernel-benchmark

gemmbench/gemm_bench.py, gemmbench/problems.py
We can filter based on 3 criteria:
1. Data types: f16/bf16
2. Matmul variants: NN, NT, TN, and TT. (NT -- transpose B)
3. Tag regex, e.g., `"unet"` or `".*skinny"`
Also fix the number of parallel compilation jobs for small machines with < 20 cores.
=> Add flags to filter gemm configs

.github/workflows/run_bench.yml, README.md, gemmbench/gemm_utils.py
This commit adapts to the recent changes made to the packaging naming in the iree-org/iree-turbine repo: https://github.com/iree-org/iree-turbine/pull/197
=> Adapt to iree-turbine naming changes.

common_tools/instruction_count.py, gemmbench/gemm_bench.py
Adds the --exec_dump_dir flag to the gemmbench script and creates a script for generating a .csv with instruction counts (naive) from dumped .rocmasm files.
By naive, I mean it starts counting lines at "Kernarg preload header" and stops at "---" to count instructions.
@kuhar is the stopping criteria here too late? it includes what seems to be metadata, so maybe it should stop at "s_endpgm" or "func_end0"?
Perhaps some of the counter utilities should be further integrated into the benchmarking tooling.
The instruction counter generates a file like this (also attached):
```
Filename,Instruction Count
./dumps/gemm_4096_640_2560_bf16/module_main_dispatch_0_rocm_hsaco_fb.rocmasm,1074
./dumps/gemm_4096_5120_640_f16_tB/module_main_dispatch_0_rocm_hsaco_fb.rocmasm,1074 …
```
=> Adds arg for exec file dump dir, instruction counter script

gemmbench/gemm_bench.py, gemmbench/gemm_utils.py, gemmbench/problems.py
For example, perform f16 matmul with f32 as the accumulator type and truncate the result to f16. This is more realistic than using f16 as the accumulator type.
Keep track of operand, accumulator, and result types in `GemmConfig`.
=> Fix accumulator and result types

attentionbench/attention_bench.py, attentionbench/attention_utils.py, common_tools/utils/bench_utils.py, convbench/conv_utils.py, convbench/shark_conv.py, gemmbench/gemm_bench.py, gemmbench/gemm_utils.py
Couple of changes in this PR
1) `--Xiree_compile` can take now a list of flags to pass to `iree-compile` without having to specify `--Xiree-compile` multiple times. Note that the flags passed to `iree-compile` should not contain `--`
2) Capture the `stderr` for `run_iree_command` and pass back to caller. This allows generating IR dumps. 
For example
`--Xiree_compile mlir-disable-threading mlir-print-ir-before=<pass-list> mlir-print-ir-after=<pass-list>` dumps IR before and after passes to `*.stderr.mlir` .
=> Update scripts to allow extra flags.

gemmbench/gemm_bench.py
Use nargs=+ for data types and variants to align with extra compiler args. This is a follow up after #10.
=> Make gemmbench flags more uniform

gemmbench/gemm_bench.py, gemmbench/gemm_utils.py, gemmbench/problems.py
A few unrelated things mixed in this PR, but they are separate commits if you'd prefer me to slice it into 3 PRs.
1. Add a `--raw_accumulators` flag that drops the truncation of the results (default False). This leads to lower arithmetic intensity (because the result values are larger) and either higher or lower performance. This is less representative of real workloads, but is sometimes easier to reason about as a microbenchmark.
2. Add support for `i8` dtype accumulating into `i32`. For now only added to the `square` problem set. Also added `bf16` to that set.
3. Add a special value for the existing `--target` flag: `"host_cpu"` for testing on CPU configured for the host. This was mostly for my own use to be able to develop these changes locally without a GPU.
=> Add support for `i8` dtype, add `--raw_accumulators` flag, add `--target=host_cpu` for easy local testing.

attentionbench/attention_utils.py
- Fix tuning spec
- Add flag for perf
- Add a dummy generation test to attention_utils
=> [attention] Fix tuning and add flags

attentionbench/problems.py
This PR adds the llama3 405b attention shapes that we see in the sharktank export (https://gist.github.com/KyleHerndon/a9c60ce93264d6ba7ec9e878c879f218). We make sure the dynamic sequence length is always a multiple of 16
=> Add llama3 405b attention shapes.

gemmbench/gemm_bench.py, gemmbench/gemm_utils.py, requirements.txt
* Use TKW `create_vmfb_file` option to get vmfb file directly
* Get scheduling params from the TK itself
* Disable scheduling for large K as compilation taking too long
* Support case when `out_type` != `accumulator_type`
* Update `exec_args` as code generated by TK expected out param to be present
* Gracefully handle TK errors instead of terminating entire script
=> Fix TKW gemm tests

.github/workflows/run_bench.yml, convbench/conv_bench.py, convbench/conv_utils.py, convbench/wave_conv_utils.py
* Add option to test TKW-based conv kernels to convbench.
* Only limited subset of datatypes is supported for now (only `f16xf16xf32`)
* Need latest iree-turbine main
=> Add TK Wave kernels to conv benchmark

attentionbench/attention_utils.py
Update attention to work ToM and support VMMA:
1. Update translation info to use "pipeline"
2. Update attention IREE IR to specify QK and KV MMA schedule separately S.T it works with ToM IREE
3. Refactor to use enum.Enum to represent intrinsics
4. Add VMMA support and helper functions to maximize perf
=> Fix attention + enable VMMA

README.md, gemmbench/gemm_utils.py
The convolution benchmarks make TK an optional dependency, not requiring it to be loaded unless you want to run the TK benchmarks.
Update the GEMM benchmarks to work similarly and update the README to make it clear that TK is optional.
=> Allow running GEMM benchmarks without Turbine installed

iree_kernel_benchmark/gemmbench/gemm_utils.py, tests/test_gemmbench_mlir_gen.py
For now, these get implicitly converted to strings when used by the IR template strings, but this still prepares for generating the entire IR with the bindings (the goal of #52).
=> Use IREE's MLIR builder Python bindings to construct gemmbench types

.github/workflows/pre-commit.yaml, .pre-commit-config.yaml, README.md, dev-requirements.txt, requirements.txt
The configuration files have been copied from https://github.com/nod-ai/shark-ai/commit/ba15477766ba5ee2212234e7585012c88c55ab32 but with some version numbers bumped.
This also splits out the development-only PIP requirements, because there's now two packages.
=> Add pre-commit hooks to do reformatting automatically

iree_kernel_benchmark/convbench/__main__.py, iree_kernel_benchmark/convbench/conv_utils.py, iree_kernel_benchmark/convbench/wave_conv_utils.py
Achieved by:
- Deduplication of tag-config pairs in the list of configs. (To this end, equality and hashing support for configs is added.)
- Using different filenames when compiling the same config with different tags.
Fixes convbench CI failures caused by a race condition, and should also be a significant efficiency improvement (40% of tag-config pairs were duplicates).
=> Prevent duplicate convbench configs clobbering eachother when compiled

iree_kernel_benchmark/gemmbench/__main__.py, iree_kernel_benchmark/gemmbench/problems.py
Essentially 759cd6f412250c9bcb09114a2d3b038966f166d7 but for gemmbench, also intended for debugging.
=> Add --config_regex option to gemmbench to allow executing a subset

.github/workflows/run_bench.yml, README.md, iree_kernel_benchmark/gemmbench/__main__.py, iree_kernel_benchmark/gemmbench/problems.py
Prior to this commit, gemmbench's problems.py hardcoded a set of datatypes for each benchmark, generating all possibilities ahead of time. The --dtypes and --raw_accumulators command-line arguments were then used to filter the resulting set of benchmarks.
This commit refactors problems.py to have less redundancy and to not hardcode any datatypes. Now only the shapes are hardcoded, and the --dtypes and --raw_accumulators command-line arguments control which datatypes are used in the result. One consequence of this is that now we get the same set of shapes no matter which datatype is requested, which provides more thorough testing for types like i8 that previously only had a very small number of hardcoded shapes.
To avoid an explosion in the amount of tests, the default set of datatypes is …
=> gemmbench: Generate benchmarks from supplied dtypes instead of filtering

.github/workflows/run_bench.yml, iree_kernel_benchmark/gemmbench/__main__.py, iree_kernel_benchmark/gemmbench/gemm_utils.py, iree_kernel_benchmark/gemmbench/problems.py, tests/test_gemmbench_mlir_gen.py
The added types are ones supported by both MLIR and IREE, and with some AMD GPU support: f8E4M3FNUZ and f8E5M2FNUZ are supported on CDNA3, whereas f8E4M3FN and f8E5M2 are supported on RDNA4. f8E4M3FNUZ is tested in CI (on MI300).
=> gemmbench: Add support for four FP8 types and test one in CI

iree_kernel_benchmark/gemmbench/gemm_utils.py, tests/test_gemmbench_mlir_gen.py
This PR drops matmul_transpose variants since transposed linalg named op variants will be dropped in https://github.com/llvm/llvm-project/pull/147961.
Issue: https://github.com/iree-org/iree/issues/21349
=> gemmbenchmark: drop matmul_transpose variants

.github/workflows/run_bench.yml, .github/workflows/short_bench.yml
Runner capacity is shifting from MI300 to MI325 machines. These machines are compatible enough for testing, though benchmarks will need new baselines.
=> Migrate existing mi300 runners to new mi325 capacity.
